Feature/integration merging manager frontends
healthSystemPSW/mainrepo pull request #43
Opened 2021-11-17 22:10 UTC by Jeckovic

2021-11-18 11:02 UTC, AleksandarRadisic approved these changes, later dismissed

2021-11-18 11:07 UTC, MilanPodunavac approved these changes, later dismissed
Navbar enjoyer

2021-11-18 11:44 UTC, stojic19 submitted a review, later dismissed

2021-11-18 13:17 UTC, AleksicNikola00 requested changes
Fix response code(change Ok to BadRequest in some cases)

2021-11-18 22:08 UTC, MilanPodunavac approved these changes, later dismissed
Promenjeno Ok u BadRequest u PharmacyCommunicationControlleru

2021-11-19 17:06 UTC, AleksicNikola00 submitted a review, later dismissed

2021-11-19 17:25 UTC, AleksicNikola00 approved these changes

2021-11-19 17:27 UTC, AleksandarRadisic approved these changes

2021-11-19 17:27 UTC, merged