Feature/integration sftp medication consumption
healthSystemPSW/mainrepo pull request #50
Opened 2021-11-20 18:00 UTC by AleksandarRadisic

Feature - Calculate medication consumption report and send it to pharmacies via Sftp server

2021-11-21 01:48 UTC, AleksicNikola00 requested changes
Delete comments and unused exceptions.

2021-11-21 15:26 UTC, AleksicNikola00 approved these changes, later dismissed

2021-11-21 15:41 UTC, stojic19 submitted a review, later dismissed

2021-11-22 16:57 UTC, MilanPodunavac approved these changes

2021-11-22 22:33 UTC, AleksicNikola00 approved these changes

2021-11-23 00:26 UTC, merged