feat: patient home page added
healthSystemPSW/mainrepo pull request #8
Opened 2021-11-05 18:22 UTC by jradman12

2021-11-05 19:04 UTC, bobabnoba approved these changes, later dismissed

2021-11-05 19:50 UTC, srdjansukovic requested changes
More components. Footer and header should be extracted to components, there should not be so much code in main component. Home page component is okay.

2021-11-07 14:54 UTC, srdjansukovic approved these changes
Everything is good now.

2021-11-07 14:56 UTC, bobabnoba approved these changes

2021-11-07 15:11 UTC, merged